import {test} from 'node:test';import assert from 'node:assert/strict';import {JSDOM} from 'jsdom';import {Store} from '../store.js';import {createApp} from '../server.js';
test('UI creates, edits, saves, reopens, duplicates, adds, wires, deletes, runs and resets',async()=>{
 const store=new Store(':memory:'),server=createApp(store);await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 const dom=new JSDOM('<div id="app"></div>',{url:base}),realFetch=globalThis.fetch,realInterval=globalThis.setInterval;let cookie='',tick;
 globalThis.window=dom.window;globalThis.document=dom.window.document;globalThis.confirm=()=>true;globalThis.setInterval=fn=>{tick=fn;return 0};globalThis.fetch=async(path,opts={})=>{const r=await realFetch(new URL(path,base),{...opts,headers:{...opts.headers,...(cookie?{cookie}:{})}});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return r};
 const $=s=>document.querySelector(s),click=s=>{assert.ok($(s),'Missing '+s);$(s).click()},input=(s,value,event='input')=>{$(s).value=value;$(s).dispatchEvent(new dom.window.Event(event,{bubbles:true}))},settle=async()=>{for(let n=0;n<100;n++){await new Promise(r=>setTimeout(r,10));if($('#save')?.textContent==='Saved'||!$('#save'))return}throw Error('Save did not settle')};
 try{await import('../public/app.js?ui');assert.equal($('#project-name').value,'Blink');input('#project-name','UI test');click('[data-action="save"]');await settle();click('[data-action="run"]');tick();assert.equal($('#runstate').textContent,'RUNNING');assert.match($('#console-output').textContent,/LED on/);click('[data-action="run"]');assert.equal($('#runstate').textContent,'PAUSED');click('[data-action="reset"]');assert.equal($('#clock').textContent,'0.00 s');click('[data-component="button"]');assert.equal(document.querySelectorAll('.circuit-component').length,4);
 const pins=[...document.querySelectorAll('[data-pin]')],a=pins.find(n=>n.getAttribute('aria-label')==='Arduino Uno pin D2'),b=pins.find(n=>n.getAttribute('aria-label')==='Push button pin 1');a.dispatchEvent(new dom.window.Event('pointerdown',{bubbles:true}));document.querySelector('[aria-label="Push button pin 1"]').dispatchEvent(new dom.window.Event('pointerdown',{bubbles:true}));assert.equal(document.querySelectorAll('.wire').length,4);
 document.querySelectorAll('.component-body')[3].dispatchEvent(new dom.window.Event('pointerdown',{bubbles:true}));click('[data-action="remove"]');assert.equal(document.querySelectorAll('.circuit-component').length,3);assert.equal(document.querySelectorAll('.wire').length,3);
 document.querySelector('[aria-label="Delete Arduino Uno"]').dispatchEvent(new dom.window.Event('pointerdown',{bubbles:true}));assert.equal(document.querySelectorAll('.circuit-component').length,2);assert.equal(document.querySelectorAll('.wire').length,1);click('[data-component="pico"]');assert.ok(document.querySelector('[aria-label="Delete Raspberry Pi Pico"]'));assert.equal(document.querySelectorAll('.circuit-component').length,3);
 input('#code','void loop(){Serial.println("tested");delay(10);}');click('[data-action="save"]');await settle();click('[data-action="dashboard"]');await new Promise(r=>setTimeout(r,30));assert.equal($('.project-open').textContent,'UI test');click('.project-open');await new Promise(r=>setTimeout(r,30));assert.match($('#code').value,/tested/);click('[data-action="duplicate"]');await new Promise(r=>setTimeout(r,50));await settle();assert.equal($('#project-name').value,'UI test copy');const list=await(await fetch('/api/projects')).json();assert.equal(list.length,2);assert.equal(list.find(p=>p.name==='UI test').wires.length,1);assert.equal(list.find(p=>p.name==='UI test').components.find(c=>c.type==='pico').type,'pico');
 }finally{globalThis.fetch=realFetch;globalThis.setInterval=realInterval;dom.window.close();await new Promise(r=>server.close(r));store.close()}
});
